<?php
/**
 * GetNetworkGroupPolicies200ResponseInnerContentFiltering
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Meraki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Meraki Dashboard API
 *
 * A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 02 April, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * The version of the OpenAPI document: 1.57.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Meraki\Model;

use \ArrayAccess;
use \Meraki\ObjectSerializer;

/**
 * GetNetworkGroupPolicies200ResponseInnerContentFiltering Class Doc Comment
 *
 * @category Class
 * @description The content filtering settings for your group policy
 * @package  Meraki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetNetworkGroupPolicies200ResponseInnerContentFiltering implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getNetworkGroupPolicies_200_response_inner_contentFiltering';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'allowed_url_patterns' => '\Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringAllowedUrlPatterns',
        'blocked_url_patterns' => '\Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringBlockedUrlPatterns',
        'blocked_url_categories' => '\Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringBlockedUrlCategories'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'allowed_url_patterns' => null,
        'blocked_url_patterns' => null,
        'blocked_url_categories' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'allowed_url_patterns' => false,
        'blocked_url_patterns' => false,
        'blocked_url_categories' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allowed_url_patterns' => 'allowedUrlPatterns',
        'blocked_url_patterns' => 'blockedUrlPatterns',
        'blocked_url_categories' => 'blockedUrlCategories'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allowed_url_patterns' => 'setAllowedUrlPatterns',
        'blocked_url_patterns' => 'setBlockedUrlPatterns',
        'blocked_url_categories' => 'setBlockedUrlCategories'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allowed_url_patterns' => 'getAllowedUrlPatterns',
        'blocked_url_patterns' => 'getBlockedUrlPatterns',
        'blocked_url_categories' => 'getBlockedUrlCategories'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('allowed_url_patterns', $data ?? [], null);
        $this->setIfExists('blocked_url_patterns', $data ?? [], null);
        $this->setIfExists('blocked_url_categories', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allowed_url_patterns
     *
     * @return \Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringAllowedUrlPatterns|null
     */
    public function getAllowedUrlPatterns()
    {
        return $this->container['allowed_url_patterns'];
    }

    /**
     * Sets allowed_url_patterns
     *
     * @param \Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringAllowedUrlPatterns|null $allowed_url_patterns allowed_url_patterns
     *
     * @return self
     */
    public function setAllowedUrlPatterns($allowed_url_patterns)
    {
        if (is_null($allowed_url_patterns)) {
            throw new \InvalidArgumentException('non-nullable allowed_url_patterns cannot be null');
        }
        $this->container['allowed_url_patterns'] = $allowed_url_patterns;

        return $this;
    }

    /**
     * Gets blocked_url_patterns
     *
     * @return \Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringBlockedUrlPatterns|null
     */
    public function getBlockedUrlPatterns()
    {
        return $this->container['blocked_url_patterns'];
    }

    /**
     * Sets blocked_url_patterns
     *
     * @param \Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringBlockedUrlPatterns|null $blocked_url_patterns blocked_url_patterns
     *
     * @return self
     */
    public function setBlockedUrlPatterns($blocked_url_patterns)
    {
        if (is_null($blocked_url_patterns)) {
            throw new \InvalidArgumentException('non-nullable blocked_url_patterns cannot be null');
        }
        $this->container['blocked_url_patterns'] = $blocked_url_patterns;

        return $this;
    }

    /**
     * Gets blocked_url_categories
     *
     * @return \Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringBlockedUrlCategories|null
     */
    public function getBlockedUrlCategories()
    {
        return $this->container['blocked_url_categories'];
    }

    /**
     * Sets blocked_url_categories
     *
     * @param \Meraki\Model\GetNetworkGroupPolicies200ResponseInnerContentFilteringBlockedUrlCategories|null $blocked_url_categories blocked_url_categories
     *
     * @return self
     */
    public function setBlockedUrlCategories($blocked_url_categories)
    {
        if (is_null($blocked_url_categories)) {
            throw new \InvalidArgumentException('non-nullable blocked_url_categories cannot be null');
        }
        $this->container['blocked_url_categories'] = $blocked_url_categories;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


