<?php
/**
 * GetNetworkSwitchDhcpServerPolicyArpInspectionTrustedServers200ResponseInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Meraki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Meraki Dashboard API
 *
 * A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 02 April, 2025 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com)
 *
 * The version of the OpenAPI document: 1.57.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Meraki\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetNetworkSwitchDhcpServerPolicyArpInspectionTrustedServers200ResponseInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetNetworkSwitchDhcpServerPolicyArpInspectionTrustedServers200ResponseInner
 * @package     Meraki
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetNetworkSwitchDhcpServerPolicyArpInspectionTrustedServers200ResponseInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetNetworkSwitchDhcpServerPolicyArpInspectionTrustedServers200ResponseInner"
     */
    public function testGetNetworkSwitchDhcpServerPolicyArpInspectionTrustedServers200ResponseInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trusted_server_id"
     */
    public function testPropertyTrustedServerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mac"
     */
    public function testPropertyMac()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vlan"
     */
    public function testPropertyVlan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ipv4"
     */
    public function testPropertyIpv4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
